import { useMemo } from "react";
import { FileText, Code2, Download } from "lucide-react";
import type { ChatMessage } from "@/lib/useChatStream";

interface Artifact {
  id: string;
  kind: "code" | "doc";
  language?: string;
  title: string;
  content: string;
}

export function ArtifactViewer({ messages }: { messages: ChatMessage[] }) {
  const artifacts = useMemo(() => extractArtifacts(messages), [messages]);

  return (
    <div>
      <div className="mb-3 text-xs font-semibold uppercase tracking-widest text-muted-foreground">
        Artifacts
      </div>
      {artifacts.length === 0 ? (
        <div className="glass rounded-xl p-4 text-xs text-muted-foreground">
          Code blocks and reports generated by Discoverse appear here, ready to download.
        </div>
      ) : (
        <div className="space-y-2">
          {artifacts.map((a) => (
            <details key={a.id} className="glass overflow-hidden rounded-xl">
              <summary className="flex cursor-pointer items-center justify-between gap-2 px-3 py-2 text-xs">
                <span className="flex items-center gap-2 truncate">
                  {a.kind === "code" ? (
                    <Code2 className="h-3.5 w-3.5 text-primary" />
                  ) : (
                    <FileText className="h-3.5 w-3.5 text-accent" />
                  )}
                  <span className="truncate font-medium">{a.title}</span>
                </span>
                <button
                  onClick={(e) => {
                    e.preventDefault();
                    download(a);
                  }}
                  className="flex shrink-0 items-center gap-1 rounded-md bg-secondary/60 px-2 py-1 text-[10px] hover:bg-secondary"
                >
                  <Download className="h-3 w-3" /> Save
                </button>
              </summary>
              <pre className="max-h-72 overflow-auto bg-black/30 p-3 font-mono text-[11px] leading-relaxed">
                <code>{a.content}</code>
              </pre>
            </details>
          ))}
        </div>
      )}
    </div>
  );
}

function extractArtifacts(messages: ChatMessage[]): Artifact[] {
  const out: Artifact[] = [];
  messages.forEach((m, i) => {
    if (m.role !== "assistant" || !m.content) return;
    const re = /```(\w+)?\n([\s\S]*?)```/g;
    let match;
    let n = 0;
    while ((match = re.exec(m.content)) !== null) {
      n++;
      const lang = match[1] || "text";
      out.push({
        id: `${m.id}-${n}`,
        kind: "code",
        language: lang,
        title: `Block ${n} · ${lang}`,
        content: match[2].trim(),
      });
    }
    // Whole message as a doc artifact
    if (m.content.length > 400 && !m.streaming) {
      out.push({
        id: `${m.id}-doc`,
        kind: "doc",
        title: `Report · message ${i + 1}`,
        content: m.content,
      });
    }
  });
  return out;
}

function download(a: Artifact) {
  const ext = a.kind === "doc" ? "md" : extForLang(a.language);
  const blob = new Blob([a.content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `discoverse-${a.id}.${ext}`;
  link.click();
  URL.revokeObjectURL(url);
}

function extForLang(lang?: string) {
  const m: Record<string, string> = {
    typescript: "ts",
    tsx: "tsx",
    javascript: "js",
    jsx: "jsx",
    python: "py",
    sql: "sql",
    bash: "sh",
    json: "json",
    yaml: "yml",
    md: "md",
    markdown: "md",
  };
  return m[lang ?? ""] ?? "txt";
}
